export const ONBOARD_FETCH = "ONBOARD_FETCH"
export const MAIN_FETCH = "MAIN_FETCH"

export const ERROR_FETCH = "ERROR_FETCH"
export const ERROR_DROP = "ERROR_DROP"
export const CONNECTINFO = "CONNECTINFO"

export const AUTH_VERIFY_PHONE = 'AUTH_VERIFY_PHONE'
export const AUTH_SEND_SMS_CODE = 'AUTH_SEND_SMS_CODE'

export const USER_CREATE = 'USER_CREATE'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_FETCH = 'USER_FETCH'
export const USER_DROP = 'USER_DROP'
export const USER_GEOLOCATION_SET = "USER_GEOLOCATION_SET"
export const USER_GEOLOCATION_DEFAULT_SET = "USER_GEOLOCATION_DEFAULT_SET"

export const PAYMENTS_CARDS_FETCH = "PAYMENTS_CARDS_FETCH"
export const PAYMENTS_CARD_CREATE = "PAYMENTS_CARD_CREATE"
export const PAYMENTS_CARD_CREATE_SUCCESS = "PAYMENTS_CARD_CREATE_SUCCESS"
export const PAYMENTS_CARD_CREATE_ERROR = "PAYMENTS_CARD_CREATE_ERROR"
export const PAYMENTS_CARD_CREATE_3DS = "PAYMENTS_CARD_CREATE_3DS"
export const PAYMENTS_CARD_DROP_3DS = "PAYMENTS_CARD_DROP_3DS"
export const PAYMENTS_CARD_DROP = "PAYMENTS_CARD_DROP"
export const PAYMENTS_CHECKS_FETCH = "PAYMENTS_CHECKS_FETCH"

export const RENT_FETCH = "RENT_FETCH"
export const RENT_START = "RENT_START"
export const RENT_FALSESTART = "RENT_FALSESTART"
export const RENT_STOP = "RENT_STOP"

export const SETTING_LOCALE_FETCH = "SETTING_LOCALE_FETCH"
export const SETTING_LOCALE_SET = "SETTING_LOCALE_SET"

export const SEARCH_ADDRESS_FETCH = "SEARCH_ADDRESS_FETCH"
export const SEARCH_ADDRESS_CLEAR = "SEARCH_ADDRESS_CLEAR"
export const SEARCH_ADD_PIN = "SEARCH_ADD_PIN"

export const STATION_POINTS_FETCH = "STATION_POINTS_FETCH"
export const STATIONS_FETCH = "STATIONS_FETCH"
export const STATION_DETAIL_FETCH = "STATION_DETAIL_FETCH"
export const STATION_DETAIL_CLEAR = "STATION_DETAIL_CLEAR"

export const STATION_ACTIVE_MARKER = "STATION_ACTIVE_MARKER"
export const STATION_DEACTIVE_MARKER = "STATION_DEACTIVE_MARKER"
export const STATION_ACTIVE_MARKER_CLEAR = "STATION_ACTIVE_MARKER_CLEAR"


export const SETTING_STYLE_OVERLAY = "SETTING_STYLE_OVERLAY"
export const SETTING_STYLE_HIDDEN_HEADER = "SETTING_STYLE_HIDDEN_HEADER"
export const SETTING_STYLE_HIDDEN_SEARCH = "SETTING_STYLE_HIDDEN_SEARCH"

export const SOCKET_CONNECTION_INIT = "SOCKET_CONNECTION_INIT"
export const SOCKET_RENT_START = "SOCKET_RENT_START"
export const SOCKET_RENT_END = "SOCKET_RENT_END"
